networks:
  fabric_test:
    external: true

volumes:
  minio_data:

services:

  # =====================================================
  # MINIO STORAGE
  # =====================================================
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - fabric_test
    restart: always




  # =====================================================
  # NESSIE METADATA CATALOG (Iceberg REST Catalog backend)
  # =====================================================
  nessie:
    image: ghcr.io/projectnessie/nessie:0.80.0
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      QUARKUS_HTTP_PORT: 19120
    networks:
      - fabric_test
    restart: always


  # =====================================================
  # TRINO SQL ENGINE
  # =====================================================
  trino:
    image: trinodb/trino:435
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
    networks:
      - fabric_test


  # =====================================================
  # LISTENER (Fabric Org2 → MinIO Bronze)
  # =====================================================
  # listener:
  #   build:
  #     context: ./listener
  #     dockerfile: Dockerfile
  #   container_name: fabric-listener
  #   volumes:
  #     - ./test-network/organizations:/crypto
  #     - ./config:/fabric-config     # ⭐ mount core.yaml vào container
  #     - ./bin/peer:/usr/local/bin/peer
  #   environment:
  #     FABRIC_CFG_PATH: /fabric-config
  #     CORE_PEER_LOCALMSPID: "Org2MSP"
  #     CORE_PEER_TLS_ENABLED: "true"
  #     CORE_PEER_ADDRESS: peer0.org2.example.com:9051
  #     CORE_PEER_MSPCONFIGPATH: /crypto/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
  #     CORE_PEER_TLS_ROOTCERT_FILE: /crypto/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt
  #   networks:
  #     - fabric_test
  #   restart: always
  listener:
    build:
      context: ./listener
      dockerfile: Dockerfile
    container_name: fabric-listener
    volumes:
      - ./test-network/organizations:/crypto
      - ./config:/fabric-config
      - ./bin:/usr/local/bin

    environment:
      FABRIC_CFG_PATH: /fabric-config
      CORE_PEER_LOCALMSPID: "Org2MSP"
      CORE_PEER_TLS_ENABLED: "true"
      CORE_PEER_ADDRESS: peer0.org2.example.com:9051
      CORE_PEER_MSPCONFIGPATH: /crypto/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
      CORE_PEER_TLS_ROOTCERT_FILE: /crypto/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt
    networks:
      - fabric_test
    restart: always




  # =====================================================
  # SPARK MASTER 3.5.0
  # =====================================================
  spark-master:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-master

    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]

    ports:
      - "7077:7077"
      - "8081:8080"
      - "4040:4040"

    environment:
      SPARK_NO_DAEMONIZE: "true"

      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin

      SPARK_DAEMON_JAVA_OPTS: >
        -Dspark.hadoop.fs.s3a.endpoint=http://minio:9000
        -Dspark.hadoop.fs.s3a.path.style.access=true
        -Dspark.hadoop.fs.s3a.connection.ssl.enabled=false

    volumes:
      - ./pipelines:/app/pipelines

    networks:
      - fabric_test
    restart: always

  # =====================================================
  # SPARK WORKER 3.5.0
  # =====================================================
  spark-worker:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-worker

    depends_on:
      - spark-master

    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.worker.Worker",
        "spark://spark-master:7077"
      ]

    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin

      SPARK_DAEMON_JAVA_OPTS: >
        -Dspark.hadoop.fs.s3a.endpoint=http://minio:9000
        -Dspark.hadoop.fs.s3a.path.style.access=true
        -Dspark.hadoop.fs.s3a.connection.ssl.enabled=false

    volumes:
      - ./pipelines:/app/pipelines

    networks:
      - fabric_test
    restart: always

